"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let dayt = new Date();
console.log(dayt);
console.log(dayt.toDateString());
console.log(dayt.toTimeString());
console.log(dayt.toLocaleString());
console.log(dayt.getFullYear());
console.log(dayt.getMonth());
console.log(dayt.getDay());
console.log(dayt.getHours());
